"""
Task to Hardware Mapping Module
===============================

This module defines classes for mapping high‑level tasks onto joint‑level
instructions.  Tasks describe what the robot should achieve (e.g.
"move arm to coordinate", "grasp object") rather than how to move
each joint.  The `TaskHardwareMapper` uses a kinematic model to
translate tasks into a sequence of joint commands that can be executed
by lower layers.

This mapping must be deterministic and free of side effects; it
should not alter global state.  All time‑critical behaviour (e.g.
trajectory execution) happens after mapping via the joint
synchroniser and hardware synchroniser.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class Task:
    """High‑level description of a robot action.

    Attributes
    ----------
    id : str
        Unique identifier of the task.
    parameters : dict
        Arbitrary key‑value parameters describing the task (e.g.
        target position, speed, force).
    """

    id: str
    parameters: dict[str, Any]


@dataclass(frozen=True)
class JointInstruction:
    """Instruction for a single joint.

    Attributes
    ----------
    joint_id : str
        Identifier of the joint to command.
    command : Any
        Platform‑specific command object (e.g. position, velocity,
        torque) generated by the mapper.  The type is intentionally
        generic; downstream modules will interpret it.
    """

    joint_id: str
    command: Any


class KinematicsModel(Protocol):
    """Protocol for a kinematic model used by the mapper.

    A kinematic model must at least implement a method to compute
    joint angles for a given end‑effector pose.  Additional methods
    may be added as needed.
    """

    def inverse_kinematics(
        self, target: dict[str, Any], current: dict[str, Any]
    ) -> dict[str, Any]: ...


class TaskHardwareMapper:
    """Map high‑level tasks to joint‑level instructions.

    Parameters
    ----------
    kinematics_model : KinematicsModel
        Model used to convert end‑effector targets into joint angles.
    """

    def __init__(self, kinematics_model: KinematicsModel) -> None:
        self._kinematics = kinematics_model

    def map_task(self, task: Task, current_state: dict[str, Any]) -> list[JointInstruction]:
        """Convert a high‑level task into joint‑level instructions.

        This implementation supports two forms of tasks:

        * **Direct joint specification:** If the task parameters
          include a ``joint_positions`` dictionary mapping joint IDs
          directly to desired positions (and optionally velocities and
          torques), those values are passed through unchanged.  This
          allows upper layers to specify exact joint targets when
          inverse kinematics is not required.

        * **Inverse kinematics:** Otherwise, the parameters are passed
          to the injected kinematics model's ``inverse_kinematics``
          method along with the current state to compute joint
          targets.

        In both cases, a list of :class:`JointInstruction` objects is
        returned.  Each instruction contains the joint ID and the
        platform‑specific command (e.g. desired position).  The
        commands are not interpreted here; downstream modules will
        convert them into actuator commands.

        Parameters
        ----------
        task : Task
            High‑level task description.
        current_state : dict[str, Any]
            Current robot state.

        Returns
        -------
        list[JointInstruction]
            Joint instructions to achieve the task.

        Raises
        ------
        ValueError
            If the task parameters are invalid.
        """
        if not isinstance(task.parameters, dict):
            raise ValueError("Task parameters must be a dictionary")
        if "joint_positions" in task.parameters:
            jp = task.parameters["joint_positions"]
            if not isinstance(jp, dict):
                raise ValueError("'joint_positions' must be a dict")
            position_instructions: list[JointInstruction] = []
            for joint_id, pos in jp.items():
                position_instructions.append(
                    JointInstruction(joint_id=joint_id, command={"position": pos})
                )
            return position_instructions

        if "target_velocity" in task.parameters:
            tv = task.parameters["target_velocity"]
            vx: float
            if isinstance(tv, (list, tuple)) and tv:
                try:
                    vx = float(tv[0])
                except Exception:
                    vx = 0.0
            else:
                if isinstance(tv, (int, float, str)):
                    try:
                        vx = float(tv)
                    except Exception:
                        vx = 0.0
                else:
                    vx = 0.0

            joint_ids: list[str] = []
            if current_state and isinstance(current_state.get("positions"), dict):
                joint_ids = list(current_state["positions"].keys())

            velocity_instructions: list[JointInstruction] = []
            for jid in joint_ids:
                velocity_instructions.append(
                    JointInstruction(joint_id=jid, command={"velocity": vx})
                )
            return velocity_instructions

        # Case 2: use inverse kinematics
        target = task.parameters
        joint_targets = self._kinematics.inverse_kinematics(target, current_state)
        instructions = []
        for joint_id, cmd in joint_targets.items():
            instructions.append(JointInstruction(joint_id=joint_id, command=cmd))
        return instructions

    def prioritize_tasks(
        self,
        tasks: list[Task],
        battery_manager: Any,
        thermal_manager: Any,
        current_state: dict[str, Any],
    ) -> list[Task]:
        """Order tasks based on estimated energy and thermal requirements.

        This helper sorts a list of tasks so that those requiring less
        energy and generating less heat are executed first.  It uses
        the provided ``battery_manager`` and ``thermal_manager`` to
        estimate resource consumption for each task by temporarily
        mapping it to joint instructions via ``map_task()``.  Tasks
        lacking meaningful parameters default to zero cost.  Any errors
        encountered during estimation are ignored and such tasks are
        treated as high cost (deferred).

        Parameters
        ----------
        tasks : list of Task
            Pending tasks to prioritise.
        battery_manager : BatteryManager
            Battery manager used to estimate energy consumption.
        thermal_manager : ThermalManager
            Thermal manager used to estimate thermal load.
        current_state : dict
            Current robot state passed to ``map_task()`` and estimation
            functions.

        Returns
        -------
        list of Task
            Tasks sorted in ascending order of resource cost.
        """
        scored: list[tuple[float, Task]] = []
        for task in tasks:
            try:
                instrs = self.map_task(task, current_state)
                energy = battery_manager.estimate_task_energy(instrs, current_state)
                thermal = thermal_manager.estimate_task_thermal_load(instrs, current_state)
                # Combine energy and thermal load into a simple score
                score = energy + thermal
            except Exception:
                # Assign a high score on error to defer this task
                score = float("inf")
            scored.append((score, task))
        scored.sort(key=lambda x: x[0])
        return [task for _, task in scored]

    # ------------------------------------------------------------------
    # Additional planning helpers
    # ------------------------------------------------------------------
    def estimate_distance_to_target(self, task: Task, current_state: dict[str, Any]) -> float:
        """Estimate the aggregate joint distance to execute a task.

        This helper computes the total absolute change in joint positions
        required by a task relative to the current state.  It handles
        both direct joint specifications (via ``joint_positions``) and
        tasks requiring inverse kinematics.  If the current state is
        missing or a joint is not present, the start position defaults
        to zero.

        Parameters
        ----------
        task : Task
            The high‑level task whose distance is to be estimated.
        current_state : dict[str, Any]
            Current positions of joints (optional).

        Returns
        -------
        float
            Sum of absolute position changes across all joints.
        """
        try:
            # Use map_task to obtain joint instructions
            instructions = self.map_task(task, current_state)
        except Exception:
            return float("inf")
        curr_pos: dict[str, float] = {}
        if current_state and isinstance(current_state.get("positions"), dict):
            curr_pos = current_state.get("positions", {})
        total_distance = 0.0
        for inst in instructions:
            jid = None
            pos = None
            if hasattr(inst, "joint_id") and hasattr(inst, "command"):
                jid = inst.joint_id
                cmd = inst.command
                if isinstance(cmd, dict):
                    pos = cmd.get("position")
            elif isinstance(inst, dict):
                jid = inst.get("joint_id")
                cmd = inst.get("command") if inst.get("command") else {}
                if isinstance(cmd, dict):
                    pos = cmd.get("position")
            if jid is None or pos is None:
                continue
            try:
                target = float(pos)
            except Exception:
                target = 0.0
            try:
                start = float(curr_pos.get(jid, 0.0))
            except Exception:
                start = 0.0
            total_distance += abs(target - start)
        return total_distance

    def assign_task_sequence(self, tasks: list[Task], current_state: dict[str, Any]) -> list[Task]:
        """Order tasks to minimise travel distance.

        This helper sorts tasks by their estimated distance from the
        current configuration, so that tasks requiring the smallest
        movements are executed first.  If the distance cannot be
        computed (e.g. invalid task parameters), such tasks are placed
        at the end.

        Parameters
        ----------
        tasks : list of Task
            List of tasks to order.
        current_state : dict
            Current robot state used for distance estimation.

        Returns
        -------
        list of Task
            Tasks sorted in ascending order of movement distance.
        """
        scored: list[tuple[float, Task]] = []
        for task in tasks:
            try:
                dist = self.estimate_distance_to_target(task, current_state)
            except Exception:
                dist = float("inf")
            scored.append((dist, task))
        scored.sort(key=lambda x: x[0])
        return [task for _, task in scored]
